stages:
  - build
  - linting
  - test

default:
  tags:
    - oberon

build-linux:
  stage: build
  script:
    - module load anaconda/3
    - conda env update -n topography-ci -f environment.yml
    - conda activate topography-ci
    - pip install .
  only:
    - merge_requests

isort:
  stage: linting
  needs:
    - job: build-linux
      optional: true
  script:
    - module load anaconda/3
    - conda activate topography-ci
    - isort . --check-only

black:
  stage: linting
  needs:
    - job: build-linux
      optional: true
  script:
    - module load anaconda/3
    - conda activate topography-ci
    - black --check .

pylint:
  stage: linting
  needs:
    - job: build-linux
      optional: true
  script:
    - module load anaconda/3
    - conda activate topography-ci
    - pylint topography

flake8:
  stage: linting
  needs:
    - job: build-linux
      optional: true
  script:
    - module load anaconda/3
    - conda activate topography-ci
    - flake8

test-linux:
  stage: test
  needs:
    - job: build-linux
      optional: true
  script:
    - module load anaconda/3
    - conda activate topography-ci
    - pytest
