stages:
  - build
  - linting
  - test

default:
  tags:
    - oberon

build-linux:
  stage: build
  script:
    - module load anaconda/3
    - conda env update -n topography-ci -f environment.yml
    - conda activate topography-ci
    - pip install .

isort:
  stage: linting
  needs: ["build-linux"]
  script:
    - module load anaconda/3
    - conda activate topography-ci
    - isort . --check-only

black:
  stage: linting
  needs: ["build-linux"]
  script:
    - module load anaconda/3
    - conda activate topography-ci
    - black --check .

pylint:
  stage: linting
  needs: ["build-linux"]
  script:
    - module load anaconda/3
    - conda activate topography-ci
    - pylint topograhy

flake8:
  stage: linting
  needs: ["build-linux"]
  script:
    - module load anaconda/3
    - conda activate topography-ci
    - flake8 topograhy

test-linux:
  stage: test
  needs: ["build-linux"]
  script:
    - module load anaconda/3
    - conda activate topography-ci
    - pytest
