stages:
  - build
  - linting

default:
  tags:
    - oberon

build-linux:
  stage: build
  script:
    - module load anaconda/3
    - conda info --envs

isort:
  stage: linting
  needs: ["build-linux"]
  script:
    - isort . --check-only

black:
  stage: linting
  needs: ["build-linux"]
  script:
    - black --check .

pylint:
  stage: linting
  needs: ["build-linux"]
  script:
    - find . -type f -name "*.py" | xargs pylint
