[project]
name = "topography"
version = "0.01"
authors = ["Maxime Poli <mpoli.pro@gmail.com>"]
readme = "README.md"

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 80

[tool.pylint.message_control]
disable = "R0913, R0902"

[tool.pylint.typecheck]
ignored-modules = "torch"

[tool.pylint.format]
max-line-length = 80

[tool.pylint.master]
ignore = "topography/utils/externals"

[tool.pytest.ini_options]
addopts = "--verbose --cov=topography --cov-report=html --cov-report=term:skip-covered"
testpaths = ["tests", "topography"]

[tool.coverage.run]
branch = false
skip_empty = true
omit = ["topography/utils/externals/*"]