name: Tests
on:
  push:
    branches: [wip]
  pull_request:
    branches: [wip]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, 3.10]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip" # caching pip dependencies
        run: python -m pip install --upgrade pip
      - name: Install topography
        run: pip install -e .[dev, testing]
      - name: Test with pytest
        run: python -m pytest
